name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 0.0.1
author: Florin Bratan <florin@leadcode.io>
homepage: https://github.com/bratan/flutter_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
