name: flutter_translate
description: The internationalization (i18n) library for Flutter. It lets you define translations for your content in different languages and switch between them easily.
version: 1.5.4
author: Jesway <hello@jesway.com>
homepage: https://github.com/jesway/flutter_device_locale

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_locale: ^0.3.3

flutter:
