name: flutter_translate
description: The internationalization (i18n) library for Flutter.
version: 0.0.2
author: Leadcode <dev@leadcode.io>
homepage: https://github.com/leadcode/flutter_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
