name: example
description: Example application for flutter_translate_preferences

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate_preferences:
    path: ../

dev_dependencies:

flutter:

  uses-material-design: true
  assets:
    - assets/i18n/
