name: example
description: Example application for flutter_translate_preferences

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_translate:
    path: ../../flutter_translate/
  flutter_translate_preferences:
    path: ../

  cupertino_icons: ^0.1.2

dev_dependencies:

flutter:

  uses-material-design: true
